### ISSUE TITLE
error

### ISSUE THREAD

**Issue by bellord13** [toviLau/date-php#6]
https://github.com/toviLau/date-php/blob/28df95e4de972a03aab358a7ce9a1936184c8f14/dist/date.js#L765

need
s: function () { return pad(Math.floor(tChars.S() % conversion.i), 2); }

**Comment by toviLau** [comment]
npm fixed at version 1.7.16

**Comment by toviLau** [comment]
npm fixed at version 1.7.16

**Comment by toviLau** [comment]
npm has been fixed in version 1.7.16
